export const CREATE_ORDER_REQUEST = ' CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = ' CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = ' CREATE_ORDER_FAILURE';

export const GET_ORDER_BY_ID__REQUEST = 'GET_ORDER_BY_ID__REQUEST'
export const GET_ORDER_BY_ID__SUCCESS = 'GET_ORDER_BY_ID__SUCCESS'
export const GET_ORDER_BY_ID__FAILURE = 'GET_ORDER_BY_ID__FAILURE'

// export const GET_ORDER_HISTORY_REQUEST = 'GET_ORDER_HISTORY_REQUEST'
// export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS'
// export const GET_ORDER_HISTORY_FAILURE = 'GET_ORDER_HISTORY_FAILURE'

// export const _REQUEST = '_REQUEST'
// export const _SUCCESS = '_SUCCESS'
// export const _FAILURE = '_FAILURE'




